AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  # EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
